sudo: required
language: node_js

node_js:
  - lts/*

services:
  - docker

before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -h 0.0.0.0

install:
  - npm install -g truffle
  - npm install

script:
  - npm run test
